trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Terraform
  - task: UseTerraform@0
    inputs:
      terraformVersion: 'latest'

  # Step 2: Initialize Terraform
  - script: |
      terraform init
    displayName: 'Terraform Init'

  # Step 3: Validate Terraform
  - script: |
      terraform validate
    displayName: 'Terraform Validate'

  # Step 4: Test Module
  - script: |
      terraform plan -var="resource_group_name=test-rg" -var="location=East US"
    displayName: 'Terraform Plan'

  # Step 5: Publish to Terraform Registry
  - script: |
      git tag v1.0.0
      git push origin v1.0.0
    displayName: 'Publish Module'
